
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador.asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int AP_BLOQUE = 30;
  public static final int CONST = 9;
  public static final int POR = 13;
  public static final int GE = 22;
  public static final int INT = 37;
  public static final int PUNTOCOMA = 27;
  public static final int REF = 40;
  public static final int AP_PAR = 28;
  public static final int NOT = 18;
  public static final int AP_CORCH = 32;
  public static final int AND = 16;
  public static final int IGUAL = 25;
  public static final int LT = 23;
  public static final int OR = 17;
  public static final int BOOL = 38;
  public static final int DIV = 14;
  public static final int IF = 2;
  public static final int LE = 24;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int TRUE = 35;
  public static final int error = 1;
  public static final int COMA = 26;
  public static final int MENOS = 12;
  public static final int NEQ = 20;
  public static final int VOID = 7;
  public static final int PUNT = 39;
  public static final int ENT = 34;
  public static final int EQU = 19;
  public static final int NEG = 15;
  public static final int CIERRE_PAR = 29;
  public static final int ELSE = 4;
  public static final int IDEN = 10;
  public static final int WHILE = 5;
  public static final int THEN = 3;
  public static final int CIERRE_CORCH = 33;
  public static final int CIERRE_BLOQUE = 31;
  public static final int FALSE = 36;
  public static final int GT = 21;
  public static final int DO = 6;
  public static final int MAS = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "VOID",
  "RETURN",
  "CONST",
  "IDEN",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "NEG",
  "AND",
  "OR",
  "NOT",
  "EQU",
  "NEQ",
  "GT",
  "GE",
  "LT",
  "LE",
  "IGUAL",
  "COMA",
  "PUNTOCOMA",
  "AP_PAR",
  "CIERRE_PAR",
  "AP_BLOQUE",
  "CIERRE_BLOQUE",
  "AP_CORCH",
  "CIERRE_CORCH",
  "ENT",
  "TRUE",
  "FALSE",
  "INT",
  "BOOL",
  "PUNT",
  "REF"
  };
}

